#!/bin/bash
# 
# Author: Stephen Rozanc
# Modified update-resolv-conf script that the OpenVPN daemon calls upon Tunnel UP and Tunnel DOWN status changes.
#
# On Tunnel UP: it writes the DNS Server advertised over the VPN to /etc/resolv.conf
# On Tunnel DOWN: it writes DEFAULT_NAMESERVER back to /etc/resolv.conf

DEFAULT_NAMESERVER="8.8.8.8"

[ "$script_type" ] || exit 0
[ "$dev" ] || exit 0

split_into_parts()
{
        part1="$1"
        part2="$2"
        part3="$3"
}

case "$script_type" in
  up)
        NMSRVRS=""
        SRCHS=""
        foreign_options=$(printf '%s\n' ${!foreign_option_*} | sort -t _ -k 3 -g)
        for optionvarname in ${foreign_options} ; do
                option="${!optionvarname}"
                echo "$option"
                split_into_parts $option
                if [ "$part1" = "dhcp-option" ] ; then
                        if [ "$part2" = "DNS" ] ; then
                                NMSRVRS="${NMSRVRS:+$NMSRVRS }$part3"
                        elif [ "$part2" = "DOMAIN" ] ; then
                                SRCHS="${SRCHS:+$SRCHS }$part3"
                        fi
                fi
        done
        R=""
        [ "$SRCHS" ] && R="search $SRCHS
"
        for NS in $NMSRVRS ; do
                R="${R}nameserver $NS
"
        done
        echo -n "$R" > /etc/resolv.conf
        ;;
  down)
        echo "nameserver ${DEFAULT_NAMESERVER}" > /etc/resolv.conf
        ;;
esac
